### ISSUE TITLE
Bug in code at line 10

### ISSUE THREAD

**Issue by veeruguru** [veeruguru/Infyproject#1]
There is bug found in the code at line 10, please fix it.

**Comment by radapa1** [comment]
oh my god issue in my code 👍

**Comment by bipeensinha** [comment]
I think it is issues of Syntax , Curly Bracket seems to be miising
![code](https://user-images.githubusercontent.com/49720823/101275022-9358f680-37c8-11eb-83e2-819d52b051f4.jpg)

**Comment by devineni25** [comment]
I don't think it's an issue. You only go back and check.  :))

**Comment by bipeensinha** [comment]
![code2](https://user-images.githubusercontent.com/49720823/101275061-d1561a80-37c8-11eb-90a7-313207ef4e89.jpg)
I solve this issues

**Comment by veeruguru** [comment]
Thanks all, issue is closed now.

**Comment by veeruguru** [comment]
This issue is fixed now.
